
homeassistant:
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  elevation: !secret ha_elevation
  unit_system: metric
  time_zone: Europe/Paris
  temperature_unit: C
  
  packages: !include_dir_named integration
  customize: !include customize.yaml


# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# configuration des log
logger:
  default: info
  logs:
# log level for HA core
    homeassistant.core: fatal

# log level for MQTT integration
    homeassistant.components.mqtt: warning

# log level for all python scripts
    homeassistant.components.python_script: warning

# individual log level for this python script
    homeassistant.components.python_script.my_new_script.py: warning

# log level for a custom component
    #custom_components.my_integration: debug
    
# log level for the `aiohttp` Python package
    aiohttp: error

# Inclusion des themes
frontend:
  themes: !include_dir_merge_named themes/


# Inclusion groupes/automatismes/script/scene
group: !include groups.yaml
automation manual: !include_dir_merge_list automations/
automation ui: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

shell_command:
  push_to_github: /config/gitpush.sh
