####################################################
#                                                  #
#                   Piscine                        #
#                   Automation                     #
####################################################

automation:
  - alias: Piscine-3_1_2-Hors-Gel
    description: ''
    trigger:
    - platform: time_pattern
      hours: /1
    - platform: state
      entity_id: input_boolean.hors_gel_valid
      id: hg_deval
      from: 'on'
      to: 'off'
    condition: []
    action:
    - choose:
      - conditions:
        - condition: numeric_state
        ## Ajout d'un capteur de temperature exterieur
          entity_id: sensor.temp_pisc_exterieur
          below: input_number.hors_gel_inf_seuil2
        - condition: state
          entity_id: input_select.mode_fonctionnement_piscine
          state: Hiver
        - condition: state
          entity_id: input_boolean.hors_gel_valid
          state: 'on'
        sequence:
        - service: input_select.select_option
          data:
            option: Ma F
          target:
            entity_id: input_select.mode_fonctionnement_piscine
        - service: notify.telegram
          data:
            message: '{{states("sensor.date_time") }}'
            title: Piscine Hors-Gel Seuil 2 Marc Ppe
        - delay:
            hours: 0
            minutes: 30
            seconds: 0
            milliseconds: 0
        - service: input_select.select_option
          target:
            entity_id: input_select.mode_fonctionnement_piscine
          data:
            option: At F
        - delay:
            hours: 0
            minutes: 0
            seconds: 2
            milliseconds: 0
        - service: input_select.select_option
          target:
            entity_id: input_select.mode_fonctionnement_piscine
          data:
            option: Hiver
        - service: notify.telegram
          data:
            message: '{{states("sensor.date_time") }}'
            title: Piscine Hors-Gel Seuil 2 Arret Ppe
      - conditions:
        - condition: numeric_state
        ## Ajout d'un capteur de temperature exterieur
          entity_id: sensor.temp_pisc_exterieur
          below: input_number.hors_gel_inf_seuil1
        - condition: state
          entity_id: input_select.mode_fonctionnement_piscine
          state: Hiver
        - condition: state
          entity_id: input_boolean.hors_gel_valid
          state: 'on'
        sequence:
        - service: input_select.select_option
          data:
            option: Ma F
          target:
            entity_id: input_select.mode_fonctionnement_piscine
        - service: notify.telegram
          data:
            message: '{{states("sensor.date_time") }}'
            title: Piscine Hors-Gel Seuil 1 Marc Ppe
        - delay:
            hours: 0
            minutes: 15
            seconds: 0
            milliseconds: 0
        - service: input_select.select_option
          target:
            entity_id: input_select.mode_fonctionnement_piscine
          data:
            option: Hiver
        - service: notify.telegram
          data:
            message: '{{states("sensor.date_time") }}'
            title: Piscine Hors-Gel Seuil 1 Arret Ppe
      - conditions:
        - condition: trigger
          id: hg_deval
        sequence:
        - service: input_select.select_option
          target:
            entity_id: input_select.mode_fonctionnement_piscine
          data:
            option: Hiver
        - service: notify.telegram
          data:
            message: '{{states("sensor.date_time") }}'
            title: Piscine Hors-Gel devalidé
      default: []
    mode: restart
    max: 10

  - alias: "Piscine-3_1_3-Notifications filtration"
    description: Debut, Fin
    trigger:
    - platform: state
      entity_id: binary_sensor.ppe_piscine_en_marche
      from: 'off'
      to: 'on'
      id: ma_ppe
    - platform: state
      entity_id: binary_sensor.ppe_piscine_en_marche
      id: at_ppe
      from: 'on'
      to: 'off'
    - platform: time
      at: '23:59'
      id: minuit
    condition: []
    action:
    - choose:
      - conditions:
        - condition: trigger
          id: ma_ppe
        sequence:
        - service: notify.telegram
          data:
            message: '{{states("sensor.date_time") }}'
            title: Piscine Début Filtration
      - conditions:
        - condition: trigger
          id: at_ppe
        sequence:
        - service: notify.telegram
          data:
            message: '{{states("sensor.date_time") }}'
            title: Piscine Fin de filtration
      - conditions:
        - condition: trigger
          id: minuit
        sequence:
        - service: notify.telegram
          data:
            message: 'Temps de filtration:  {{states.sensor.ma_ppe_piscine_jour.attributes.value}}{{-"\n"-}}Conso:
              {{states(''sensor.energie_piscine_jour'')}} kWh.{{-"\n"-}} Tps Utilisation
              cart. Chlore: {{states(''input_number.temps_cartouche_chlore'')}} h {{-"\n"-}}{{states("sensor.date_time")
              }}'
            title: Piscine Rapport Fin de journée
        - service: notify.log_piscine
          data:
            message: '{{states.sensor.ma_ppe_piscine_jour.attributes.value }},{{states(''sensor.energie_piscine_jour'')}}'
            title: Rapport jour piscine
      default: []
    mode: single

  - alias: "Piscine-3_1_5-Pression-haute"
    description: ''
    trigger:
    - platform: numeric_state
      entity_id: sensor.f_pression_filtre
      above: '0.8'
      for:
        hours: 0
        minutes: 15
        seconds: 0
        milliseconds: 0
    condition: []
    action:
    - service: notify.telegram
      data:
        message: Pression Haute = {{states("sensor.f_pression_filtre") }}{{-"\n"-}}{{states("sensor.date_time")
          }}
        title: Piscine Alerte Pression Filtre !!!
    mode: single

####### Heure plein Heure Creuse
  - alias: "Piscine-6_1_0-Energie Changement HP/HC"
    description: 'Energie Changement Heure Pleine/Heure Creuse'
    trigger:
#    - platform: state
#      entity_id: sensor.linky_n_tarif
#      id: tarif_hc
#      from: '2'
#      to: '1'
#    - platform: state
#      entity_id: sensor.linky_n_tarif
#      from: '1'
#      id: tarif_hp
#      to: '2'
      - platform: time
        at: '21:30:00'
        id: tarif_hc
      - platform: time
        at: '05:00:00'
        id: tarif_hp
    condition: []
    action:
    - choose:
      - conditions:
        - condition: trigger
          id: tarif_hc
        sequence:
        - service: select.select_option
          data:
            option: hc
          target:
            entity_id:
            - select.energy_pisc_usage_daily
            - select.energy_pisc_usage_weekly
            - select.energy_pisc_usage_monthly
            - select.energy_pisc_usage_yearly
      - conditions:
        - condition: trigger
          id: tarif_hp
        sequence:
        - service: select.select_option
          data:
            option: hp
          target:
            entity_id:
            - select.energy_pisc_usage_daily
            - select.energy_pisc_usage_weekly
            - select.energy_pisc_usage_monthly
            - select.energy_pisc_usage_yearly
      default: []
    mode: single