####################################################
#                                                  #
#                   Piscine                        #
#                   Automation                     #
####################################################


automation:
  - alias: Piscine-3_4_1-EV-Appoint-EAU
    description: "Piscine Appoint Eau uniquement si volet ouvert depuis 15 mn"
    trigger:
    - platform: state
      entity_id:
      - cover.volet_piscine
      to: open
      for:
        hours: 0
        minutes: 15
        seconds: 0
      id: vol_ouv
    - platform: state
      entity_id: input_boolean.ev_eau_piscine
      to: 'on'
      id: valid_ev
      from: 'off'
    - platform: state
      entity_id: input_boolean.ev_eau_piscine
      id: devalid_ev
      to: 'off'
      from: 'on'
    - platform: state
      entity_id: binary_sensor.tp_plein_lsh
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 0
        seconds: 20
      id: lsh_off
    condition: []
    action:
    - choose:
      - conditions:
        - condition: trigger
          id: vol_ouv
        - condition: state
          entity_id: input_boolean.ev_eau_piscine
          state: 'on'
        - condition: state
          entity_id: binary_sensor.tp_plein_lsh
          state: 'on'
        sequence:
        - service: switch.turn_on
          target:
            entity_id: switch.ev_eau
          data: {}
        - service: notify.telegram
          data:
            message: Ouverture EV Eau {{-"\n"-}}{{states("sensor.date_time") }}
            title: Piscine Appoint Eau!
      - conditions:
        - condition: state
          entity_id: switch.ev_eau
          state: 'on'
        - condition: or
          conditions:
          - condition: trigger
            id: devalid_ev
          - condition: trigger
            id: lsh_off
        sequence:
        - service: switch.turn_off
          target:
            entity_id: switch.ev_eau
          data: {}
        - service: notify.telegram
          data:
            message: Fermeture EV Eau {{-"\n"-}}{{states("sensor.date_time") }}
            title: Piscine Appoint Eau!
      default: []
    mode: single

  - alias: Piscine-3_4_2-Notification-Alarme-Ajout-Eau
    description: "Piscine Notification Alarme Appoint d'eau"
    trigger:
    - platform: numeric_state
      entity_id: sensor.ev_eau_tps_ouverture_jour
      above: '1.00'
    condition: []
    action:
    - service: notify.telegram
      data:
        message: Temps ouverture supérieur à {{states('sensor.ev_eau_tps_ouverture_jour')}}
          h{{-"\n"-}}{{states("sensor.date_time") }}
        title: Alarme EV Appoint d'eau Piscine
    - service: switch.turn_off
      target:
        entity_id: switch.ev_eau
    mode: single

  - alias: Piscine-3_4_3-Notification-niveau-bas
    description: "Piscine Notification alarme niveau bas"
    trigger:
    - platform: state
      entity_id: binary_sensor.tp_plein_lsl
      from: 'off'
      to: 'on'
      for: 00:00:10
    condition: []
    action:
    - service: notify.telegram
      data:
        title: ALARME
        message: Niveau bas Piscine
    - service: input_select.select_option
      data:
        option: 'Off'
      target:
        entity_id: input_select.mode_fonctionnement_piscine_test
    - service: notify.telegram
      data:
        message: Niveau bas piscine{{-"\n"-}}{{states("sensor.date_time") }}{{-"\n"-}}{{states("sensor.date_time")
          }}
        title: Piscine Alarme Niveau Bas !!!
    mode: single
    